// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/comments.tsx";
import * as $3 from "./routes/extras.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/CurrentTime.tsx";
import * as $$1 from "./islands/LocaleDate.tsx";
import * as $$2 from "./islands/TimeTilBirthday.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/comments.tsx": $2,
    "./routes/extras.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/CurrentTime.tsx": $$0,
    "./islands/LocaleDate.tsx": $$1,
    "./islands/TimeTilBirthday.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
